name: Run QA Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Automation/requirements.txt
      - name: Run UI tests
        run: |
          pytest Automation/tests -q --html=report.html
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html
